
package com.reactiveworks.mart.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Tue Mar 17 11:42:32 PDT 2020
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getProductCategoriesResponse", namespace = "http://mart.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductCategoriesResponse", namespace = "http://mart.reactiveworks.com/")

public class GetProductCategoriesResponse {

    @XmlElement(name = "name_m")
    private java.util.List<java.lang.String> name_m;

    public java.util.List<java.lang.String> getName_m() {
        return this.name_m;
    }

    public void setName_m(java.util.List<java.lang.String> newName_m)  {
        this.name_m = newName_m;
    }

}

