
package com.reactiveworks.productservice.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-20T17:12:12.588-07:00
 * Generated source version: 3.2.12
 */

@WebFault(name = "DataBaseAccessFailureException", targetNamespace = "http://service.productservice.reactiveworks.com/")
public class DataBaseAccessFailureException_Exception extends Exception {

    private com.reactiveworks.productservice.service.DataBaseAccessFailureException dataBaseAccessFailureException;

    public DataBaseAccessFailureException_Exception() {
        super();
    }

    public DataBaseAccessFailureException_Exception(String message) {
        super(message);
    }

    public DataBaseAccessFailureException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DataBaseAccessFailureException_Exception(String message, com.reactiveworks.productservice.service.DataBaseAccessFailureException dataBaseAccessFailureException) {
        super(message);
        this.dataBaseAccessFailureException = dataBaseAccessFailureException;
    }

    public DataBaseAccessFailureException_Exception(String message, com.reactiveworks.productservice.service.DataBaseAccessFailureException dataBaseAccessFailureException, java.lang.Throwable cause) {
        super(message, cause);
        this.dataBaseAccessFailureException = dataBaseAccessFailureException;
    }

    public com.reactiveworks.productservice.service.DataBaseAccessFailureException getFaultInfo() {
        return this.dataBaseAccessFailureException;
    }
}
