
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.reactiveworks.productservice.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-20T17:12:12.593-07:00
 * Generated source version: 3.2.12
 *
 */

@javax.jws.WebService(
                      serviceName = "ProductWebServiceService",
                      portName = "ProductWebServicePort",
                      targetNamespace = "http://service.productservice.reactiveworks.com/",
                      wsdlLocation = "file:/C:/Users/reactiveworks13/new/client/WebContent/wsdl/productwebservice.wsdl",
                      endpointInterface = "com.reactiveworks.productservice.service.ProductWebService")

public class ProductWebServicePortImpl implements ProductWebService {

    private static final Logger LOG = Logger.getLogger(ProductWebServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.reactiveworks.productservice.service.ProductWebService#insertProduct(com.reactiveworks.productservice.service.Product arg0)*
     */
    public void insertProduct(com.reactiveworks.productservice.service.Product arg0) throws UnableToReadPropertyFileException_Exception,  DataBaseAccessFailureException_Exception   {
        LOG.info("Executing operation insertProduct");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UnableToReadPropertyFileException_Exception("UnableToReadPropertyFileException...");
        //throw new DataBaseAccessFailureException_Exception("DataBaseAccessFailureException...");
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.productservice.service.ProductWebService#getProducts()*
     */
    public java.util.List<com.reactiveworks.productservice.service.Product> getProducts() throws UnableToReadPropertyFileException_Exception,  DataBaseAccessFailureException_Exception   {
        LOG.info("Executing operation getProducts");
        try {
            java.util.List<com.reactiveworks.productservice.service.Product> _return = new java.util.ArrayList<com.reactiveworks.productservice.service.Product>();
            com.reactiveworks.productservice.service.Product _returnVal1 = new com.reactiveworks.productservice.service.Product();
            _returnVal1.setManufecturedDt(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-20T17:12:12.605-07:00"));
            _returnVal1.setProductId(-1901345547);
            _returnVal1.setProductName("ProductName2079355594");
            _returnVal1.setProductType("ProductType1566266756");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UnableToReadPropertyFileException_Exception("UnableToReadPropertyFileException...");
        //throw new DataBaseAccessFailureException_Exception("DataBaseAccessFailureException...");
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.productservice.service.ProductWebService#deleteProduct(int arg0)*
     */
    public void deleteProduct(int arg0) throws UnableToReadPropertyFileException_Exception,  DataBaseAccessFailureException_Exception   {
        LOG.info("Executing operation deleteProduct");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UnableToReadPropertyFileException_Exception("UnableToReadPropertyFileException...");
        //throw new DataBaseAccessFailureException_Exception("DataBaseAccessFailureException...");
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.productservice.service.ProductWebService#getProduct(int arg0)*
     */
    public com.reactiveworks.productservice.service.Product getProduct(int arg0) throws UnableToReadPropertyFileException_Exception,  DataBaseAccessFailureException_Exception   {
        LOG.info("Executing operation getProduct");
        System.out.println(arg0);
        try {
            com.reactiveworks.productservice.service.Product _return = new com.reactiveworks.productservice.service.Product();
            _return.setManufecturedDt(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-20T17:12:12.607-07:00"));
            _return.setProductId(1230639971);
            _return.setProductName("ProductName-784411053");
            _return.setProductType("ProductType-1762262334");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UnableToReadPropertyFileException_Exception("UnableToReadPropertyFileException...");
        //throw new DataBaseAccessFailureException_Exception("DataBaseAccessFailureException...");
    }

}
