package com.reactiveworks.productservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-20T17:12:12.609-07:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://service.productservice.reactiveworks.com/", name = "ProductWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductWebService {

    @WebMethod
    @RequestWrapper(localName = "insertProduct", targetNamespace = "http://service.productservice.reactiveworks.com/", className = "com.reactiveworks.productservice.service.InsertProduct")
    @ResponseWrapper(localName = "insertProductResponse", targetNamespace = "http://service.productservice.reactiveworks.com/", className = "com.reactiveworks.productservice.service.InsertProductResponse")
    public void insertProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        com.reactiveworks.productservice.service.Product arg0
    ) throws UnableToReadPropertyFileException_Exception, DataBaseAccessFailureException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://service.productservice.reactiveworks.com/", className = "com.reactiveworks.productservice.service.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://service.productservice.reactiveworks.com/", className = "com.reactiveworks.productservice.service.GetProductsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.reactiveworks.productservice.service.Product> getProducts() throws UnableToReadPropertyFileException_Exception, DataBaseAccessFailureException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://service.productservice.reactiveworks.com/", className = "com.reactiveworks.productservice.service.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://service.productservice.reactiveworks.com/", className = "com.reactiveworks.productservice.service.DeleteProductResponse")
    public void deleteProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws UnableToReadPropertyFileException_Exception, DataBaseAccessFailureException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://service.productservice.reactiveworks.com/", className = "com.reactiveworks.productservice.service.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://service.productservice.reactiveworks.com/", className = "com.reactiveworks.productservice.service.GetProductResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.reactiveworks.productservice.service.Product getProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws UnableToReadPropertyFileException_Exception, DataBaseAccessFailureException_Exception;
}
