
package com.reactiveworks.productservice.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-20T17:12:12.581-07:00
 * Generated source version: 3.2.12
 */

@WebFault(name = "UnableToReadPropertyFileException", targetNamespace = "http://service.productservice.reactiveworks.com/")
public class UnableToReadPropertyFileException_Exception extends Exception {

    private com.reactiveworks.productservice.service.UnableToReadPropertyFileException unableToReadPropertyFileException;

    public UnableToReadPropertyFileException_Exception() {
        super();
    }

    public UnableToReadPropertyFileException_Exception(String message) {
        super(message);
    }

    public UnableToReadPropertyFileException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UnableToReadPropertyFileException_Exception(String message, com.reactiveworks.productservice.service.UnableToReadPropertyFileException unableToReadPropertyFileException) {
        super(message);
        this.unableToReadPropertyFileException = unableToReadPropertyFileException;
    }

    public UnableToReadPropertyFileException_Exception(String message, com.reactiveworks.productservice.service.UnableToReadPropertyFileException unableToReadPropertyFileException, java.lang.Throwable cause) {
        super(message, cause);
        this.unableToReadPropertyFileException = unableToReadPropertyFileException;
    }

    public com.reactiveworks.productservice.service.UnableToReadPropertyFileException getFaultInfo() {
        return this.unableToReadPropertyFileException;
    }
}
