
package com.reactiveworks.employee.service.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Wed Mar 18 10:44:20 PDT 2020
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "insertEmployeeResponse", namespace = "http://impl.service.employee.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "insertEmployeeResponse", namespace = "http://impl.service.employee.reactiveworks.com/")

public class InsertEmployeeResponse {


}

