
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.reactiveworks.practice.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-20T10:24:46.865-07:00
 * Generated source version: 3.2.12
 *
 */

@javax.jws.WebService(
                      serviceName = "StudentInfoWebServiceService",
                      portName = "StudentInfoWebServicePort",
                      targetNamespace = "http://webservice.practice.reactiveworks.com/",
                      wsdlLocation = "file:/C:/Users/reactiveworks13/soap/webserviceclient/WebContent/wsdl/studentinfowebservice.wsdl",
                      endpointInterface = "com.reactiveworks.practice.webservice.StudentInfoWebService")

public class StudentInfoWebServicePortImpl implements StudentInfoWebService {

    private static final Logger LOG = Logger.getLogger(StudentInfoWebServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.reactiveworks.practice.webservice.StudentInfoWebService#getStudents()*
     */
    public java.util.List<com.reactiveworks.practice.webservice.Student> getStudents() throws ParseException_Exception   {
        LOG.info("Executing operation getStudents");
        try {
            java.util.List<com.reactiveworks.practice.webservice.Student> _return = new java.util.ArrayList<com.reactiveworks.practice.webservice.Student>();
            com.reactiveworks.practice.webservice.Student _returnVal1 = new com.reactiveworks.practice.webservice.Student();
            _returnVal1.setDob(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-03-20T10:24:46.874-07:00"));
            _returnVal1.setName("Name-1849889900");
            _returnVal1.setPercentage(0.6768474333108881);
            _returnVal1.setRollNo(1481848464);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ParseException_Exception("ParseException...");
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.practice.webservice.StudentInfoWebService#insertStudent(com.reactiveworks.practice.webservice.Student arg0)*
     */
    public void insertStudent(com.reactiveworks.practice.webservice.Student arg0) {
        LOG.info("Executing operation insertStudent");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.practice.webservice.StudentInfoWebService#deleteStudent(int arg0)*
     */
    public void deleteStudent(int arg0) {
        LOG.info("Executing operation deleteStudent");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
