package com.reactiveworks.practice.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-20T10:24:46.882-07:00
 * Generated source version: 3.2.12
 *
 */
@WebServiceClient(name = "StudentInfoWebServiceService",
                  wsdlLocation = "file:/C:/Users/reactiveworks13/soap/webserviceclient/WebContent/wsdl/studentinfowebservice.wsdl",
                  targetNamespace = "http://webservice.practice.reactiveworks.com/")
public class StudentInfoWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.practice.reactiveworks.com/", "StudentInfoWebServiceService");
    public final static QName StudentInfoWebServicePort = new QName("http://webservice.practice.reactiveworks.com/", "StudentInfoWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/reactiveworks13/soap/webserviceclient/WebContent/wsdl/studentinfowebservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentInfoWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/reactiveworks13/soap/webserviceclient/WebContent/wsdl/studentinfowebservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentInfoWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentInfoWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentInfoWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StudentInfoWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentInfoWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentInfoWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StudentInfoWebService
     */
    @WebEndpoint(name = "StudentInfoWebServicePort")
    public StudentInfoWebService getStudentInfoWebServicePort() {
        return super.getPort(StudentInfoWebServicePort, StudentInfoWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentInfoWebService
     */
    @WebEndpoint(name = "StudentInfoWebServicePort")
    public StudentInfoWebService getStudentInfoWebServicePort(WebServiceFeature... features) {
        return super.getPort(StudentInfoWebServicePort, StudentInfoWebService.class, features);
    }

}
