
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.reactiveworks.employee.endpoint;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T15:42:21.027-07:00
 * Generated source version: 3.2.12
 *
 */

@javax.jws.WebService(
                      serviceName = "EmployeesDataService",
                      portName = "EmployeesDataPort",
                      targetNamespace = "http://endpoint.employee.reactiveworks.com/",
                      wsdlLocation = "file:/C:/Users/reactiveworks13/soap-practice/EmployeeTopDownExmple/WebContent/wsdl/employee.wsdl",
                      endpointInterface = "com.reactiveworks.employee.endpoint.EmployeesData")

public class EmployeesDataPortImpl implements EmployeesData {

    private static final Logger LOG = Logger.getLogger(EmployeesDataPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.reactiveworks.employee.endpoint.EmployeesData#getEmployees()*
     */
    public java.util.List<com.reactiveworks.employee.endpoint.Employee> getEmployees() {
        LOG.info("Executing operation getEmployees");
        try {
            java.util.List<com.reactiveworks.employee.endpoint.Employee> _return = new java.util.ArrayList<com.reactiveworks.employee.endpoint.Employee>();
            com.reactiveworks.employee.endpoint.Employee _returnVal1 = new com.reactiveworks.employee.endpoint.Employee();
            _returnVal1.setEmpName("EmpName-1459805999");
            _returnVal1.setEmpNo(1210539509);
            _returnVal1.setSalary(0.4760778558238822);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.employee.endpoint.EmployeesData#insertEmployee(com.reactiveworks.employee.endpoint.Employee employee)*
     */
    public void insertEmployee(com.reactiveworks.employee.endpoint.Employee employee) {
        LOG.info("Executing operation insertEmployee");
        System.out.println(employee);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.employee.endpoint.EmployeesData#deleteEmployee(java.lang.Integer rollNo)*
     */
    public void deleteEmployee(javax.xml.ws.Holder<java.lang.Integer> rollNo) {
        LOG.info("Executing operation deleteEmployee");
        System.out.println(rollNo.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
