package com.reactiveworks.employee.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T15:42:21.088-07:00
 * Generated source version: 3.2.12
 *
 */
@WebServiceClient(name = "EmployeesDataService",
                  wsdlLocation = "file:/C:/Users/reactiveworks13/soap-practice/EmployeeTopDownExmple/WebContent/wsdl/employee.wsdl",
                  targetNamespace = "http://endpoint.employee.reactiveworks.com/")
public class EmployeesDataService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.employee.reactiveworks.com/", "EmployeesDataService");
    public final static QName EmployeesDataPort = new QName("http://endpoint.employee.reactiveworks.com/", "EmployeesDataPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/reactiveworks13/soap-practice/EmployeeTopDownExmple/WebContent/wsdl/employee.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeesDataService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/reactiveworks13/soap-practice/EmployeeTopDownExmple/WebContent/wsdl/employee.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeesDataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeesDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeesDataService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EmployeesDataService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EmployeesDataService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EmployeesDataService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EmployeesData
     */
    @WebEndpoint(name = "EmployeesDataPort")
    public EmployeesData getEmployeesDataPort() {
        return super.getPort(EmployeesDataPort, EmployeesData.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeesData
     */
    @WebEndpoint(name = "EmployeesDataPort")
    public EmployeesData getEmployeesDataPort(WebServiceFeature... features) {
        return super.getPort(EmployeesDataPort, EmployeesData.class, features);
    }

}
