package com.reactiveworks.employee.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T15:42:21.080-07:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://endpoint.employee.reactiveworks.com/", name = "EmployeesData")
@XmlSeeAlso({ObjectFactory.class})
public interface EmployeesData {

    @WebMethod
    @RequestWrapper(localName = "getEmployees", targetNamespace = "http://endpoint.employee.reactiveworks.com/", className = "com.reactiveworks.employee.endpoint.GetEmployees")
    @ResponseWrapper(localName = "getEmployeesResponse", targetNamespace = "http://endpoint.employee.reactiveworks.com/", className = "com.reactiveworks.employee.endpoint.GetEmployeesResponse")
    @WebResult(name = "response", targetNamespace = "http://endpoint.employee.reactiveworks.com/")
    public java.util.List<com.reactiveworks.employee.endpoint.Employee> getEmployees();

    @WebMethod
    @RequestWrapper(localName = "insertEmployee", targetNamespace = "http://endpoint.employee.reactiveworks.com/", className = "com.reactiveworks.employee.endpoint.InsertEmployee")
    @ResponseWrapper(localName = "insertEmployeeResponse", targetNamespace = "http://endpoint.employee.reactiveworks.com/", className = "com.reactiveworks.employee.endpoint.InsertEmployeeResponse")
    public void insertEmployee(
        @WebParam(name = "employee", targetNamespace = "http://endpoint.employee.reactiveworks.com/")
        com.reactiveworks.employee.endpoint.Employee employee
    );

    @WebMethod
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://endpoint.employee.reactiveworks.com/", className = "com.reactiveworks.employee.endpoint.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployee", targetNamespace = "http://endpoint.employee.reactiveworks.com/", className = "com.reactiveworks.employee.endpoint.DeleteEmployee")
    public void deleteEmployee(
        @WebParam(mode = WebParam.Mode.INOUT, name = "rollNo", targetNamespace = "http://endpoint.employee.reactiveworks.com/")
        javax.xml.ws.Holder<java.lang.Integer> rollNo
    );
}
