
package com.reactiveworks.employee.repository.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Wed Mar 18 10:22:03 PDT 2020
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getEmployeesResponse", namespace = "http://repository.employee.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEmployeesResponse", namespace = "http://repository.employee.reactiveworks.com/")

public class GetEmployeesResponse {

    @XmlElement(name = "return")
    private java.util.List<com.reactiveworks.employee.model.Employee> _return;

    public java.util.List<com.reactiveworks.employee.model.Employee> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.reactiveworks.employee.model.Employee> new_return)  {
        this._return = new_return;
    }

}

