
package com.reactiveworks.mart.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Tue Mar 17 11:45:54 PDT 2020
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getProductCategories", namespace = "http://mart.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductCategories", namespace = "http://mart.reactiveworks.com/")

public class GetProductCategories {


}

