package com.reactiveworks.practice.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T18:06:17.899-07:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://webservice.practice.reactiveworks.com/", name = "StudentInfoWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentInfoWebService {

    @WebMethod
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://webservice.practice.reactiveworks.com/", className = "com.reactiveworks.practice.webservice.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://webservice.practice.reactiveworks.com/", className = "com.reactiveworks.practice.webservice.GetStudentsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.reactiveworks.practice.webservice.Student> getStudents() throws ParseException_Exception;

    @WebMethod
    @RequestWrapper(localName = "insertStudent", targetNamespace = "http://webservice.practice.reactiveworks.com/", className = "com.reactiveworks.practice.webservice.InsertStudent")
    @ResponseWrapper(localName = "insertStudentResponse", targetNamespace = "http://webservice.practice.reactiveworks.com/", className = "com.reactiveworks.practice.webservice.InsertStudentResponse")
    public void insertStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        com.reactiveworks.practice.webservice.Student arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteStudent", targetNamespace = "http://webservice.practice.reactiveworks.com/", className = "com.reactiveworks.practice.webservice.DeleteStudent")
    @ResponseWrapper(localName = "deleteStudentResponse", targetNamespace = "http://webservice.practice.reactiveworks.com/", className = "com.reactiveworks.practice.webservice.DeleteStudentResponse")
    public void deleteStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
