
package com.reactiveworks.mart.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Mar 13 16:54:16 PDT 2020
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getProductCategories", namespace = "http://service.mart.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductCategories", namespace = "http://service.mart.reactiveworks.com/")

public class GetProductCategories {


}

