
package com.reactiveworks.practice.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.12
 * Thu Mar 19 18:04:44 PDT 2020
 * Generated source version: 3.2.12
 */

@XmlRootElement(name = "getStudentsResponse", namespace = "http://webservice.practice.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getStudentsResponse", namespace = "http://webservice.practice.reactiveworks.com/")

public class GetStudentsResponse {

    @XmlElement(name = "return")
    private java.util.List<com.reactiveworks.practice.model.Student> _return;

    public java.util.List<com.reactiveworks.practice.model.Student> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.reactiveworks.practice.model.Student> new_return)  {
        this._return = new_return;
    }

}

