
package com.reactiveworks.practice.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.12
 * Thu Mar 19 18:04:44 PDT 2020
 * Generated source version: 3.2.12
 */

@XmlRootElement(name = "insertStudent", namespace = "http://webservice.practice.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "insertStudent", namespace = "http://webservice.practice.reactiveworks.com/")

public class InsertStudent {

    @XmlElement(name = "arg0")
    private com.reactiveworks.practice.model.Student arg0;

    public com.reactiveworks.practice.model.Student getArg0() {
        return this.arg0;
    }

    public void setArg0(com.reactiveworks.practice.model.Student newArg0)  {
        this.arg0 = newArg0;
    }

}

