package com.reactiveworks.student.repository;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T12:24:55.525-07:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://repository.student.reactiveworks.com/", name = "StudentsData")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentsData {

    @WebMethod
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://repository.student.reactiveworks.com/", className = "com.reactiveworks.student.repository.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://repository.student.reactiveworks.com/", className = "com.reactiveworks.student.repository.GetStudentsResponse")
    public void getStudents(
        @WebParam(mode = WebParam.Mode.OUT, name = "name", targetNamespace = "http://repository.student.reactiveworks.com/")
        javax.xml.ws.Holder<java.lang.String> name,
        @WebParam(mode = WebParam.Mode.OUT, name = "rollNo", targetNamespace = "http://repository.student.reactiveworks.com/")
        javax.xml.ws.Holder<java.lang.Integer> rollNo,
        @WebParam(mode = WebParam.Mode.OUT, name = "percentage", targetNamespace = "http://repository.student.reactiveworks.com/")
        javax.xml.ws.Holder<java.lang.Double> percentage
    );
}
