
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.reactiveworks.student.repository;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T12:24:55.472-07:00
 * Generated source version: 3.2.12
 *
 */

@javax.jws.WebService(
                      serviceName = "StudentsDataService",
                      portName = "StudentsDataPort",
                      targetNamespace = "http://repository.student.reactiveworks.com/",
                      wsdlLocation = "file:/C:/Users/reactiveworks13/soap-practice/StudentTopDown/WebContent/wsdl/student.wsdl",
                      endpointInterface = "com.reactiveworks.student.repository.StudentsData")

public class StudentsDataPortImpl implements StudentsData {

    private static final Logger LOG = Logger.getLogger(StudentsDataPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.reactiveworks.student.repository.StudentsData#getStudents(java.lang.String name, java.lang.Integer rollNo, java.lang.Double percentage)*
     */
    public void getStudents(javax.xml.ws.Holder<java.lang.String> name, javax.xml.ws.Holder<java.lang.Integer> rollNo, javax.xml.ws.Holder<java.lang.Double> percentage) {
        LOG.info("Executing operation getStudents");
        try {
            java.lang.String nameValue = "nameValue2119954487";
            name.value = nameValue;
            int rollNoValue = 1279712306;
            rollNo.value = rollNoValue;
            double percentageValue = 0.9502279443289093;
            percentage.value = percentageValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
