
package com.reactiveworks.productservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.12
 * Fri Mar 20 19:18:19 PDT 2020
 * Generated source version: 3.2.12
 */

@XmlRootElement(name = "getProductsResponse", namespace = "http://service.productservice.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductsResponse", namespace = "http://service.productservice.reactiveworks.com/")

public class GetProductsResponse {

    @XmlElement(name = "return")
    private java.util.List<com.reactiveworks.productservice.model.Product> _return;

    public java.util.List<com.reactiveworks.productservice.model.Product> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.reactiveworks.productservice.model.Product> new_return)  {
        this._return = new_return;
    }

}

