
package com.reactiveworks.productservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.12
 * Fri Mar 20 19:18:19 PDT 2020
 * Generated source version: 3.2.12
 */

@XmlRootElement(name = "getProducts", namespace = "http://service.productservice.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProducts", namespace = "http://service.productservice.reactiveworks.com/")

public class GetProducts {


}

