
package com.reactiveworks.productservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.12
 * Fri Mar 20 19:18:20 PDT 2020
 * Generated source version: 3.2.12
 */

@XmlRootElement(name = "ParseException", namespace = "http://text.java/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParseException", namespace = "http://text.java/", propOrder = {"errorOffset", "message"})

public class ParseExceptionBean {

    private int errorOffset;
    private java.lang.String message;

    public int getErrorOffset() {
        return this.errorOffset;
    }

    public void setErrorOffset(int newErrorOffset)  {
        this.errorOffset = newErrorOffset;
    }

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

