package com.reactiveworks.mart;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T11:29:30.743-07:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://mart.reactiveworks.com/", name = "name")
@XmlSeeAlso({ObjectFactory.class})
public interface Name {

    @WebMethod
    @RequestWrapper(localName = "getProductByCategory", targetNamespace = "http://mart.reactiveworks.com/", className = "com.reactiveworks.mart.GetProductByCategory")
    @ResponseWrapper(localName = "getProductByCategoryResponse", targetNamespace = "http://mart.reactiveworks.com/", className = "com.reactiveworks.mart.GetProductByCategoryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getProductByCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://mart.reactiveworks.com/", className = "com.reactiveworks.mart.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://mart.reactiveworks.com/", className = "com.reactiveworks.mart.AddProductResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getProductCategories", targetNamespace = "http://mart.reactiveworks.com/", className = "com.reactiveworks.mart.GetProductCategories")
    @ResponseWrapper(localName = "getProductCategoriesResponse", targetNamespace = "http://mart.reactiveworks.com/", className = "com.reactiveworks.mart.GetProductCategoriesResponse")
    @WebResult(name = "name_m", targetNamespace = "")
    public java.util.List<java.lang.String> getProductCategories();
}
