
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.reactiveworks.mart;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T11:29:30.689-07:00
 * Generated source version: 3.2.12
 *
 */

@javax.jws.WebService(
                      serviceName = "servicename",
                      portName = "portname",
                      targetNamespace = "http://mart.reactiveworks.com/",
                      wsdlLocation = "file:/C:/Users/reactiveworks13/soap-practice/topDown1/WebContent/wsdl/productcatalog.wsdl",
                      endpointInterface = "com.reactiveworks.mart.Name")

public class PortnameImpl implements Name {

    private static final Logger LOG = Logger.getLogger(PortnameImpl.class.getName());

    /* (non-Javadoc)
     * @see com.reactiveworks.mart.Name#getProductByCategory(java.lang.String arg0)*
     */
    public java.util.List<java.lang.String> getProductByCategory(java.lang.String arg0) {
        LOG.info("Executing operation getProductByCategory");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-912216204";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.mart.Name#addProduct(java.lang.String arg0, java.lang.String arg1)*
     */
    public boolean addProduct(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation addProduct");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.mart.Name#getProductCategories()*
     */
    public java.util.List<java.lang.String> getProductCategories() {
        LOG.info("Executing operation getProductCategories");
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-742420959";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
