package com.reactiveworks.mart;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T11:29:30.751-07:00
 * Generated source version: 3.2.12
 *
 */
@WebServiceClient(name = "servicename",
                  wsdlLocation = "file:/C:/Users/reactiveworks13/soap-practice/topDown1/WebContent/wsdl/productcatalog.wsdl",
                  targetNamespace = "http://mart.reactiveworks.com/")
public class Servicename extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mart.reactiveworks.com/", "servicename");
    public final static QName Portname = new QName("http://mart.reactiveworks.com/", "portname");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/reactiveworks13/soap-practice/topDown1/WebContent/wsdl/productcatalog.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Servicename.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/reactiveworks13/soap-practice/topDown1/WebContent/wsdl/productcatalog.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Servicename(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Servicename(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Servicename() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Servicename(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Servicename(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Servicename(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Name
     */
    @WebEndpoint(name = "portname")
    public Name getPortname() {
        return super.getPort(Portname, Name.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Name
     */
    @WebEndpoint(name = "portname")
    public Name getPortname(WebServiceFeature... features) {
        return super.getPort(Portname, Name.class, features);
    }

}
