package com.reactiveworks.productservice.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-20T19:19:52.418-07:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://service.productservice.reactiveworks.com/", name = "ProductWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductWebService {

    @WebMethod
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://service.productservice.reactiveworks.com/", className = "com.reactiveworks.productservice.service.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://service.productservice.reactiveworks.com/", className = "com.reactiveworks.productservice.service.GetProductsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.reactiveworks.productservice.service.Product> getProducts() throws ParseException_Exception;
}
