package com.reactiveworks.student.repository;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T15:02:32.672-07:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://repository.student.reactiveworks.com/", name = "StudentsData")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentsData {

    @WebMethod
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://repository.student.reactiveworks.com/", className = "com.reactiveworks.student.repository.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://repository.student.reactiveworks.com/", className = "com.reactiveworks.student.repository.GetStudentResponse")
    @WebResult(name = "response", targetNamespace = "http://repository.student.reactiveworks.com/")
    public com.reactiveworks.student.repository.Student getStudent(
        @WebParam(name = "arg1", targetNamespace = "http://repository.student.reactiveworks.com/")
        int arg1
    ) throws DaoOperationFailureException_Exception, DataSourceAccessFailureDaoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://repository.student.reactiveworks.com/", className = "com.reactiveworks.student.repository.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://repository.student.reactiveworks.com/", className = "com.reactiveworks.student.repository.GetStudentsResponse")
    @WebResult(name = "response", targetNamespace = "http://repository.student.reactiveworks.com/")
    public java.util.List<com.reactiveworks.student.repository.Student> getStudents() throws DaoOperationFailureException_Exception, DataSourceAccessFailureDaoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteStudent", targetNamespace = "http://repository.student.reactiveworks.com/", className = "com.reactiveworks.student.repository.DeleteStudent")
    @ResponseWrapper(localName = "deleteStudentResponse", targetNamespace = "http://repository.student.reactiveworks.com/", className = "com.reactiveworks.student.repository.DeleteStudentResponse")
    public void deleteStudent(
        @WebParam(name = "arg1", targetNamespace = "http://repository.student.reactiveworks.com/")
        int arg1
    ) throws DaoOperationFailureException_Exception, DataSourceAccessFailureDaoException_Exception;
}
