
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.reactiveworks.student.repository;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T15:02:32.654-07:00
 * Generated source version: 3.2.12
 *
 */

@javax.jws.WebService(
                      serviceName = "StudentsDataService",
                      portName = "StudentsDataPort",
                      targetNamespace = "http://repository.student.reactiveworks.com/",
                      wsdlLocation = "file:/C:/Users/reactiveworks13/soap-practice/StudentWebServiceTopDown/WebContent/wsdl/student.wsdl",
                      endpointInterface = "com.reactiveworks.student.repository.StudentsData")

public class StudentsDataPortImpl implements StudentsData {

    private static final Logger LOG = Logger.getLogger(StudentsDataPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.reactiveworks.student.repository.StudentsData#getStudent(int arg1)*
     */
    public com.reactiveworks.student.repository.Student getStudent(int arg1) throws DaoOperationFailureException_Exception,  DataSourceAccessFailureDaoException_Exception   {
        LOG.info("Executing operation getStudent");
        System.out.println(arg1);
        try {
            com.reactiveworks.student.repository.Student _return = new com.reactiveworks.student.repository.Student();
            _return.setName("Name1248183327");
            _return.setRollNo(270142334);
            _return.setPercentage(0.7467901655417024);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DaoOperationFailureException_Exception("DaoOperationFailureException...");
        //throw new DataSourceAccessFailureDaoException_Exception("DataSourceAccessFailureDaoException...");
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.student.repository.StudentsData#getStudents()*
     */
    public java.util.List<com.reactiveworks.student.repository.Student> getStudents() throws DaoOperationFailureException_Exception,  DataSourceAccessFailureDaoException_Exception   {
        LOG.info("Executing operation getStudents");
        try {
            java.util.List<com.reactiveworks.student.repository.Student> _return = new java.util.ArrayList<com.reactiveworks.student.repository.Student>();
            com.reactiveworks.student.repository.Student _returnVal1 = new com.reactiveworks.student.repository.Student();
            _returnVal1.setName("Name256294865");
            _returnVal1.setRollNo(614236047);
            _returnVal1.setPercentage(0.05828181831537682);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DaoOperationFailureException_Exception("DaoOperationFailureException...");
        //throw new DataSourceAccessFailureDaoException_Exception("DataSourceAccessFailureDaoException...");
    }

    /* (non-Javadoc)
     * @see com.reactiveworks.student.repository.StudentsData#deleteStudent(int arg1)*
     */
    public void deleteStudent(int arg1) throws DaoOperationFailureException_Exception,  DataSourceAccessFailureDaoException_Exception   {
        LOG.info("Executing operation deleteStudent");
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DaoOperationFailureException_Exception("DaoOperationFailureException...");
        //throw new DataSourceAccessFailureDaoException_Exception("DataSourceAccessFailureDaoException...");
    }

}
