
package com.reactiveworks.practice.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-20T16:52:42.270-07:00
 * Generated source version: 3.2.12
 */

@WebFault(name = "DaoOperationFailureException", targetNamespace = "http://endpoint.practice.reactiveworks.com/")
public class DaoOperationFailureException_Exception extends Exception {

    private com.reactiveworks.practice.endpoint.DaoOperationFailureException daoOperationFailureException;

    public DaoOperationFailureException_Exception() {
        super();
    }

    public DaoOperationFailureException_Exception(String message) {
        super(message);
    }

    public DaoOperationFailureException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DaoOperationFailureException_Exception(String message, com.reactiveworks.practice.endpoint.DaoOperationFailureException daoOperationFailureException) {
        super(message);
        this.daoOperationFailureException = daoOperationFailureException;
    }

    public DaoOperationFailureException_Exception(String message, com.reactiveworks.practice.endpoint.DaoOperationFailureException daoOperationFailureException, java.lang.Throwable cause) {
        super(message, cause);
        this.daoOperationFailureException = daoOperationFailureException;
    }

    public com.reactiveworks.practice.endpoint.DaoOperationFailureException getFaultInfo() {
        return this.daoOperationFailureException;
    }
}
