
package com.reactiveworks.practice.endpoint;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-20T16:52:42.228-07:00
 * Generated source version: 3.2.12
 *
 */
public final class StudentWebService_StudentWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://endpoint.practice.reactiveworks.com/", "StudentWebServiceService");

    private StudentWebService_StudentWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = StudentWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        StudentWebServiceService ss = new StudentWebServiceService(wsdlURL, SERVICE_NAME);
        StudentWebService port = ss.getStudentWebServicePort();

        {
        System.out.println("Invoking getStudent...");
        int _getStudent_arg0 = 1263976167;
        try {
            com.reactiveworks.practice.endpoint.Student _getStudent__return = port.getStudent(_getStudent_arg0);
            System.out.println("getStudent.result=" + _getStudent__return);

        } catch (DaoOperationFailureException_Exception e) {
            System.out.println("Expected exception: DaoOperationFailureException has occurred.");
            System.out.println(e.toString());
        } catch (DataSourceAccessFailureDaoException_Exception e) {
            System.out.println("Expected exception: DataSourceAccessFailureDaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getStudents...");
        try {
            java.util.List<com.reactiveworks.practice.endpoint.Student> _getStudents__return = port.getStudents();
            System.out.println("getStudents.result=" + _getStudents__return);

        } catch (DaoOperationFailureException_Exception e) {
            System.out.println("Expected exception: DaoOperationFailureException has occurred.");
            System.out.println(e.toString());
        } catch (DataSourceAccessFailureDaoException_Exception e) {
            System.out.println("Expected exception: DataSourceAccessFailureDaoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteStudent...");
        int _deleteStudent_arg0 = 1724866107;
        try {
            port.deleteStudent(_deleteStudent_arg0);

        } catch (DaoOperationFailureException_Exception e) {
            System.out.println("Expected exception: DaoOperationFailureException has occurred.");
            System.out.println(e.toString());
        } catch (DataSourceAccessFailureDaoException_Exception e) {
            System.out.println("Expected exception: DataSourceAccessFailureDaoException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
