package com.reactiveworks.practice.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-20T16:52:42.299-07:00
 * Generated source version: 3.2.12
 *
 */
@WebServiceClient(name = "StudentWebServiceService",
                  wsdlLocation = "file:/C:/Users/reactiveworks13/new/SchoolClient/WebContent/wsdl/studentwebservice.wsdl",
                  targetNamespace = "http://endpoint.practice.reactiveworks.com/")
public class StudentWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.practice.reactiveworks.com/", "StudentWebServiceService");
    public final static QName StudentWebServicePort = new QName("http://endpoint.practice.reactiveworks.com/", "StudentWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/reactiveworks13/new/SchoolClient/WebContent/wsdl/studentwebservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/reactiveworks13/new/SchoolClient/WebContent/wsdl/studentwebservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StudentWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StudentWebService
     */
    @WebEndpoint(name = "StudentWebServicePort")
    public StudentWebService getStudentWebServicePort() {
        return super.getPort(StudentWebServicePort, StudentWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentWebService
     */
    @WebEndpoint(name = "StudentWebServicePort")
    public StudentWebService getStudentWebServicePort(WebServiceFeature... features) {
        return super.getPort(StudentWebServicePort, StudentWebService.class, features);
    }

}
