package com.reactiveworks.practice;

import com.reactiveworks.practice.webservice.ParseException_Exception;
import com.reactiveworks.practice.webservice.StudentInfoWebService;
import com.reactiveworks.practice.webservice.StudentInfoWebServiceService;

public class Test {

	public static void main(String[] args) throws ParseException_Exception {

		/*
		 * org.apache.cxf.jaxws.JaxWsProxyFactoryBean factory = new
		 * org.apache.cxf.jaxws.JaxWsProxyFactoryBean();
		 * 
		 * factory.getInInterceptors().add(new LoggingInInterceptor());
		 * 
		 * factory.getOutInterceptors().add(new LoggingOutInterceptor());
		 * 
		 * // Utilize the class which was auto-generated by Apache CXF wsdl2java for
		 * service interface
		 * 
		 * factory.setServiceClass(StudentInfoWebService.class);
		 * 
		 * // Use the endpoint URL for your web service
		 * 
		 * factory.setAddress(
		 * "http://localhost:8080/StudentWebService/services/StudentInfoWebServicePort")
		 * ;
		 * 
		 * 
		 * 
		 * StudentInfoWebService port = (StudentInfoWebService) factory.create();
		 * 
		 * 
		 * 
		 * org.apache.cxf.endpoint.Client client =
		 * org.apache.cxf.frontend.ClientProxy.getClient(port);
		 * 
		 * org.apache.cxf.transport.http.HTTPConduit httpConduit =
		 * (org.apache.cxf.transport.http.HTTPConduit) client.getConduit();
		 * 
		 * org.apache.cxf.configuration.security.AuthorizationPolicy authorization =
		 * httpConduit.getAuthorization();
		 * 
		 * authorization.setUserName("tomcat");
		 * 
		 * authorization.setPassword("tomcat");
		 * 
		 * long timeout = 10000L;
		 * 
		 * org.apache.cxf.transports.http.configuration.HTTPClientPolicy policy = new
		 * org.apache.cxf.transports.http.configuration.HTTPClientPolicy();
		 * 
		 * policy.setConnectionTimeout(timeout);
		 * 
		 * policy.setReceiveTimeout(timeout);
		 * 
		 * httpConduit.setClient(policy);
		 */
//		port.getStudents(); // // StudentInfoWebServiceService service = new
//		StudentInfoWebServiceService(); // StudentInfoWebService port =
//		service.getStudentInfoWebServicePort(); // port.getStudents();
		
		StudentInfoWebServiceService service=new StudentInfoWebServiceService();
		StudentInfoWebService port = service.getStudentInfoWebServicePort();
		port.getStudents();
	}

}
