package com.reactiveworks.student.repository;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-19T13:00:38.026-07:00
 * Generated source version: 3.2.12
 *
 */
@WebServiceClient(name = "StudentsDataService",
                  wsdlLocation = "file:/C:/Users/reactiveworks13/soap-practice/StudentTopDownExample/WebContent/wsdl/student.wsdl",
                  targetNamespace = "http://repository.student.reactiveworks.com/")
public class StudentsDataService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://repository.student.reactiveworks.com/", "StudentsDataService");
    public final static QName StudentsDataPort = new QName("http://repository.student.reactiveworks.com/", "StudentsDataPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/reactiveworks13/soap-practice/StudentTopDownExample/WebContent/wsdl/student.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentsDataService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/reactiveworks13/soap-practice/StudentTopDownExample/WebContent/wsdl/student.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentsDataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentsDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentsDataService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StudentsDataService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentsDataService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentsDataService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StudentsData
     */
    @WebEndpoint(name = "StudentsDataPort")
    public StudentsData getStudentsDataPort() {
        return super.getPort(StudentsDataPort, StudentsData.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentsData
     */
    @WebEndpoint(name = "StudentsDataPort")
    public StudentsData getStudentsDataPort(WebServiceFeature... features) {
        return super.getPort(StudentsDataPort, StudentsData.class, features);
    }

}
