
package com.reactiveworks.practice.endpoint.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Wed Mar 18 09:51:22 PDT 2020
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "DaoOperationFailureException", namespace = "http://exceptions.dao.practice.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DaoOperationFailureException", namespace = "http://exceptions.dao.practice.reactiveworks.com/")

public class DaoOperationFailureExceptionBean {

    private java.lang.String message;

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

