
package com.reactiveworks.practice.endpoint.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Tue Mar 17 16:36:30 PDT 2020
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getStudentsResponse", namespace = "http://endpoint.practice.reactiveworks.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getStudentsResponse", namespace = "http://endpoint.practice.reactiveworks.com/")

public class GetStudentsResponse {

    @XmlElement(name = "return")
    private java.util.List<com.reactiveworks.practice.model.Student> _return;

    public java.util.List<com.reactiveworks.practice.model.Student> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.reactiveworks.practice.model.Student> new_return)  {
        this._return = new_return;
    }

}

